# Generated by Django 5.2.4 on 2025-07-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbagedetection',
            old_name='detected_at',
            new_name='detections_today',
        ),
    ]
