# Generated by Django 5.2.4 on 2025-07-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_detected_at_garbagedetection_detections_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagedetection',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
