# Generated by Django 5.2.4 on 2025-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_garbagedetection_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagedetection',
            name='verify',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
